version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: guardian-postgres
    environment:
      - POSTGRES_DB=guardian
      - POSTGRES_USER=guardian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-guardian_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guardian"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: guardian-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://guardian:${POSTGRES_PASSWORD:-guardian_pass}@postgres:5432/guardian
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-https://guardian-app.com/auth/callback}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret}
      - LLM_API_URL=${LLM_API_URL:-http://localhost:1234/v1/chat/completions}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-qwen3-30b-a3b@q4_M}
      - FLASK_ENV=production
      - CORS_ORIGINS=http://localhost:3000,http://frontend,https://guardian-app.com
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "5051:5051"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5051/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: guardian-frontend
    depends_on:
      - backend
    environment:
      - NGINX_PORT=80
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  default:
    name: guardian-net