# =============================================================================
# Prometheus Configuration for GUARDIAN Monitoring
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'guardian-production'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # GUARDIAN Backend API
  - job_name: 'guardian-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    metric_relabel_configs:
      # Add instance labels
      - source_labels: [__address__]
        target_label: instance
        replacement: 'guardian-backend'
      
      # Add service label
      - target_label: service
        replacement: 'guardian'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_.*'
        target_label: service
        replacement: 'system'

  # Redis metrics (if redis exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metric_relabel_configs:
      - target_label: service
        replacement: 'redis'

  # Docker metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    metric_relabel_configs:
      - target_label: service
        replacement: 'docker'

  # GUARDIAN Health Checks
  - job_name: 'guardian-health'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /api/health/prometheus
    scrape_interval: 60s
    scrape_timeout: 30s
    metric_relabel_configs:
      - target_label: service
        replacement: 'guardian-health'

  # Custom application metrics
  - job_name: 'guardian-custom'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /api/metrics/custom
    scrape_interval: 60s
    params:
      include: ['analysis', 'documents', 'reports']
    metric_relabel_configs:
      - target_label: service
        replacement: 'guardian-application'

# Remote write configuration (for external monitoring systems)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     headers:
#       authorization: "Bearer YOUR_TOKEN"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    # Optimize for pharmaceutical analysis workloads
    min-block-duration: 2h
    max-block-duration: 25h

# Web configuration
web:
  console.libraries: /etc/prometheus/console_libraries
  console.templates: /etc/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: true
  
  # External URL for Grafana integration
  external-url: http://localhost:9090